### ISSUE TITLE
How can I get all matchs back?

### ISSUE THREAD

**Issue by eromoe** [pxpeterxu/react-regexr#1]
Hi, 

I appreciate this project. I am building a annotator,  the flow is
1. label many texts
2. use regex tools to test above labeled texts  in one page (multiple SourceEditors),
3. for each text(SourceEditor),  check match's  range is same as my annotation.

I have achieved the 1 and 2,  but I don't see how to get matches on `SourceEditor` ,
so is there any way to get matches?

**Comment by pxpeterxu** [comment]
I'm not sure if I fully understand, but based on what I know, you can just use the vanilla Javascript `new RegExp('pattern', 'gi').exec('string to match pattern against')` if you're using code similar to the following:

```js
<ExpressionEditor
  pattern={this.state.pattern}
  flags={this.state.modifiers}
  onPatternChange={this.handlePatternChange}
  onFlagsChange={this.handleFlagsChange}
  width="100%"
/>
<SourceEditor
  pattern={this.state.pattern}
  flags={this.state.modifiers}
  text={this.state.text}
  onTextChange={this.handleTextChange}
/>
```

You can have a separate method that just does

```js
const {pattern, modifiers, text} = this.state;
const re = new RegExp(pattern, modifiers);

let matches = [];
let match;

if (re.global) {
  while ((match = re.exec(text)) != null) {
    matches.push(match);
  }
} else {
  if ((match = re.exec(text)) != null) {
    matches.push(match);
  }
}
```

**Comment by eromoe** [comment]
Thank you . So execute `re.exec` twice .  hm. I am just afraid the performance would be bad if there are very many text in same page .
